spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/quizizz?TimeZone=Asia/Ho_Chi_Minh}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      initialization-fail-timeout: 60000

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  docker:
    compose:
      enabled: ${SPRING_DOCKER_COMPOSE_ENABLED:true}
      lifecycle-management: start-and-stop
      file: src/main/docker/services.yml
      stop:
        command: down
      skip:
        in-tests: true
      readiness:
        wait: always
        timeout: 5m

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  public-endpoint: ${MINIO_PUBLIC_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin123}

jwt:
  secret-key: ${JWT_SECRET_KEY:820370665f3840fdd097ddfef080afea0260702bc53f27901c61034467ab98a4d02962b5a058e6e297006f8849bf4686186f6f917f9471bcca4eaeca76c64cd4}
